#pragma once

#define APPLICATION_ROLE_TX 0u
#define APPLICATION_ROLE_RX 1u

#define ACTIVE_APPLICATION_ROLE APPLICATION_ROLE_TX

#define TX_MODE_CAPTURE_SWEEPS 0u
#define TX_MODE_CHECK_THEN_TRANSMIT 1u
#define TX_MODE_BYPASS_TO_TRANSMIT 2u

#define ACTIVE_TX_MODE TX_MODE_BYPASS_TO_TRANSMIT

#define REFLECTOMETRY_SWEEP_START_HZ 0u
#define REFLECTOMETRY_SWEEP_END_HZ 12000000u
#define REFLECTOMETRY_SWEEP_STEPS 100u
#define REFLECTOMETRY_SWEEP_DELAY_MS 370u
#define REFLECTOMETRY_SWEEP_COUNT 4u
#define REFLECTOMETRY_ADC_SAMPLES_PER_STEP 16u
#define REFLECTOMETRY_AMPLITUDE 63u

#define OOK_TEST_AMPLITUDE 40u
#define OOK_TEST_FREQUENCY_HZ 250000u
#define OOK_TEST_CHARACTER 'E'
#define OOK_SYMBOL_PERIOD_TICKS 188u

#define HEALTH_TOLERANCE_PERCENT 5u
#define HEALTH_MIN_TOLERANCE_COUNTS 3u
#define HEALTH_MAX_ALLOWED_FAILS 10u
