#pragma once

#define APPLICATION_ROLE_TX 0u
#define APPLICATION_ROLE_RX 1u

#ifndef ACTIVE_APPLICATION_ROLE
#define ACTIVE_APPLICATION_ROLE APPLICATION_ROLE_TX
#endif

#define TX_MODE_CAPTURE_SWEEPS 0u
#define TX_MODE_CHECK_THEN_TRANSMIT 1u
#define TX_MODE_BYPASS_TO_TRANSMIT 2u
#define TX_MODE_CARRIER_TEST 3u
#define TX_MODE_UART_HEARTBEAT 4u

#ifndef ACTIVE_TX_MODE
#define ACTIVE_TX_MODE TX_MODE_UART_HEARTBEAT
#endif

#define REFLECTOMETRY_SWEEP_START_HZ 0u
#define REFLECTOMETRY_SWEEP_END_HZ 12000000u
#define REFLECTOMETRY_SWEEP_STEPS 100u
#define REFLECTOMETRY_SWEEP_DELAY_MS 370u
#define REFLECTOMETRY_SWEEP_COUNT 4u
#define REFLECTOMETRY_ADC_SAMPLES_PER_STEP 16u
#define REFLECTOMETRY_AMPLITUDE 63u

#define OOK_TEST_AMPLITUDE 40u
#define OOK_TEST_FREQUENCY_HZ 20000u
#define OOK_TEST_CHARACTER 'E'
#define OOK_SYMBOL_PERIOD_TICKS 188u
#define OOK_CARRIER_TEST_ON_MS 100u
#define OOK_CARRIER_TEST_OFF_MS 100u
#define UART_HEARTBEAT_PERIOD_MS 1000u

#define RX_TEST_ADC_SAMPLES_PER_WINDOW 256u
#define RX_TEST_SPAN_THRESHOLD_COUNTS 100u

#define HEALTH_TOLERANCE_PERCENT 5u
#define HEALTH_MIN_TOLERANCE_COUNTS 3u
#define HEALTH_MAX_ALLOWED_FAILS 10u
